service: <%= ENV["SERVICE_NAME"] %>
image: <%= ENV["DOCKER_USERNAME"] %>/<%= ENV["SERVICE_NAME"] %>

servers:
  web:
    - <%= ENV["REMOTE_SERVER_IP"] %>

proxy:
  ssl: true
  app_port: 80
  hosts:
    - <%= ENV["REMOTE_DOMAIN"] %>

registry:
  username: <%= ENV["DOCKER_USERNAME"] %>
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
<% unless ENV["CI"] %>
  remote: ssh://<%= ENV["REMOTE_SERVER_USER"] %>@<%= ENV["REMOTE_SERVER_IP"] %>
<% end %>

ssh:
  user: <%= ENV["REMOTE_SERVER_USER"] %>

aliases:
  logs: app logs -f
  shell: app exec --interactive --reuse "sh"
